### ISSUE TITLE
qlib/data/storage/db_storage.py第112行return res这里res上下文中均没有定义

### ISSUE THREAD

**Issue by hugo2046** [hanson-young/qlib-pg-ext#1]
qlib/data/storage/db_storage.py第112行return res这里res上下文中均没有定义

**Comment by hanson-young** [comment]
看样子测试的时候代码未执行到这里过，应该把res设置为[]

**Comment by hugo2046** [comment]
> 看样子测试的时候代码未执行到这里过，应该把res设置为[]

谢谢！
